### ISSUE TITLE
url blocked

### ISSUE THREAD

**Issue by antoniovalladolid** [mbilling/PBIConnectors#11]
Hello,
I'm new to Power bi. Your connector seems great to me, it is an incredible solution, but I still can not get the facebook page to work, and neither does facebook ads.

The following message appears:
blocked url: an error occurred in the address because the URI is not included in the whitelist of the Oauth client configuration of the application. Verify that Oauth client access and Oauth web access are enabled, and add all domains in the application, such as valid Oauth redirect URIs.
(attached image)

Please, if it was not too much trouble, could you tell me in screenshots how should I make the connection? What should I configure exactly?
I would like to test your connectors.
I tried watching youtube tutorials but none of them managed to help me. :(

Thank you very much for your help

![captura](https://user-images.githubusercontent.com/29613217/52015307-ac4b3f00-24af-11e9-81d5-648da762c66d.PNG)

**Comment by mbilling** [comment]
Have you created a facebook app and insert the keys, https://github.com/mbilling/pbiconnectors#the-facebook-ads-insight-connector

"Valid OAuth Redirect URIs" mus be set in FB app
![image](https://user-images.githubusercontent.com/973790/52042196-d434b400-253c-11e9-8152-6ca451ddf7b0.png)

Did you try the prebuilt connectors here http://www.scitylana.com/connectors

**Comment by antoniovalladolid** [comment]
A query as I do to edit the file: 
FacebookAds \ WebApp.json 
as I do to add the client ID & secret client to the file. With what program do I edit it?

**Comment by antoniovalladolid** [comment]
I need to know how to create an app on Facebook to use its connector. Can you help me please

**Comment by ARTKB** [comment]
> Have you created a facebook app and insert the keys, https://github.com/mbilling/pbiconnectors#the-facebook-ads-insight-connector
> 
> "Valid OAuth Redirect URIs" mus be set in FB app
> ![image](https://user-images.githubusercontent.com/973790/52042196-d434b400-253c-11e9-8152-6ca451ddf7b0.png)
> 
> Did you try the prebuilt connectors here http://www.scitylana.com/connectors

Done this, with the Facebook Page connector but it still gives me the same error message as above. Any thoughts as to why?

**Comment by antoniovalladolid** [comment]
I see this error

[
![image](https://user-images.githubusercontent.com/29613217/52215288-bbd8d800-2861-11e9-80dd-58b24af04b7a.png)
](url)

**Comment by mbilling** [comment]
Can you try and download the built connector from the Scitylana website and see if you get the same error?
https://www.scitylana.com/connectors

**Comment by antoniovalladolid** [comment]
is the connector downloaded from the scitylana website

**Comment by antoniovalladolid** [comment]
I see the same error for connectors facebook pages and facebook ads,

**Comment by ARTKB** [comment]
> Can you try and download the built connector from the Scitylana website and see if you get the same error?
> https://www.scitylana.com/connectors

I have used the built connectors from the website and I get the same error.

**Comment by antoniovalladolid** [comment]
Hi. Could you find out what the error is? Why does that error appear?

**Comment by mbilling** [comment]
I can’t reproduce your error. Can you create a video showing all the steps you do from download all the way to the error?

**Comment by antoniovalladolid** [comment]
[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by antoniovalladolid** [comment]
Hi. Could you check what errors are due?
