### ISSUE TITLE
Error on Schedule refresh

### ISSUE THREAD

**Issue by byeloff** [mbilling/PBIConnectors#12]
Hi, 

When I try to configure the automatic Schedule refresh in the WEB version of PowerBI I get the following errors:

You can not schedule the update for this dataset because the following data sources currently do not support the update:
Data source for "Facebook Active Ad Action Values"
Data source for "Facebook Active Ad Actions"
Data source for "Facebook Active Ad Insights"
Data source for "Facebook Ad Action Values"
Data source for "Facebook Ad Actions"
Data source for "Facebook All Ad Insights"
Data source for "Facebook All Ad Insights (2)"
Data source for "Facebook Ad Action Values (2)"
Data source for "Facebook Active Ad Actions (2)"

Query contains unknown function name: Facebook AdsAds

Can someone help me?

Thank you

**Comment by schikulski** [comment]
I'm getting the same error for my report:

`You can't schedule refresh for this dataset because the following data sources currently don't support refresh:
Data source for "Facebook All Ad Insights"
Discover Data Sources
Query contains unknown function name: FacebookAds.Ads`

**Comment by mbilling** [comment]
Did you download the latest built connector from https://www.scitylana.com/connectors or did you build it yourself from this repo?
I just released a connector that works in services too. But it's not publshed in this repo yet. I'll push changes soon.

**Comment by mbilling** [comment]
Tested and it works. Let me know if you still have feedback. Changes will be commited
