### ISSUE TITLE
Scheduled refresh not working for FacebookAds

### ISSUE THREAD

**Issue by schikulski** [mbilling/PBIConnectors#18]
Hi. I'm getting the following error when trying to schedule a automatic refresh using the Facebook.Ads connector.

> You can't schedule refresh for this dataset because the following data sources currently don't support refresh:
Data source for "Facebook All Ad Insights"
Discover Data Sources
Query contains unknown function name: FacebookAds.Ads

Refreshing the data works inside of PowerBI Desktop, but not when published.

I'm getting the following error too:
![Unknown](https://user-images.githubusercontent.com/1258744/65498588-72a2ca80-debc-11e9-9f5d-781af2662e20.jpeg)

Any ideas?

I downloaded the connector from  https://www.scitylana.com/connectors, not building from scratch.

**Comment by mbilling** [comment]
@schikulski Did you use the pre-built from www.scitylana.com/connectors and did you install a Power Bi Gateway (personal/Enterprise)
The code provided on GitHub doesn't yet support refresh.

**Comment by mbilling** [comment]
I just committed the latest changes to GitHub. :)

**Comment by schikulski** [comment]
> @schikulski Did you use the pre-built from [www.scitylana.com/connectors](http://www.scitylana.com/connectors) and did you install a Power Bi Gateway (personal/Enterprise)
> The code provided on GitHub doesn't yet support refresh.

Yes, I downloaded the pre-built from scitylana.com. Is this supposed to work? Yes, I have the gateway running for other connectors.

**Comment by mbilling** [comment]
This works and has been working for a while.

**Comment by jorgerodri1918** [comment]
which data source should be selected at the gateway?. BI Connector?
