### ISSUE TITLE
Please HELP! connected_instagram_account not connect...

### ISSUE THREAD

**Issue by moretgn2018** [mbilling/PBIConnectors#21]
I have created the app on developers.facebook.com and when starting powerbi all the facebook pages are displayed but when choosing one that I have linked instagram-facebook the tables are not loaded because this error appears:

The 'connected_instagram_account' field of the record was not found.

what's going on? how can I solve it? many thanks!!!

**Comment by mbilling** [comment]
Previously I have seen the same behaviour.
Is seems (my conclusion) to be an old error in the Facebook backend config of the connection between the Instagram Business Account and the Facebook page.
Some users never encounter  this issue.
Completely disconnecting and re-connecting the Instagram Business Account from the Facebook page have solved it for me.
