### ISSUE TITLE
Facebook oAuth Dialog window does not close

### ISSUE THREAD

**Issue by spijs** [mbilling/PBIConnectors#22]
I am currently experiencing the issue that the facebook dialog window does not close after trying to confirm. Therefore during testing I do not see any access token returning.

I have tried this with multiple application IDs, FB api versions and always experience the same behaviour. 

Any suggestions?

**Comment by mbilling** [comment]
Try using the keyboard to navigate the UI
Use the TAB and SPACE keys

PBI uses Internet Explorer internally Facebook doesn’t support IE anymore

lør. 29. feb. 2020 kl. 13.00 skrev Thijs Dieltjens <notifications@github.com

**Comment by spijs** [comment]
While I did figure out it probably had something to do with IE popping up, that still is a nifty solution I didn't try yet 👍 . Thanks it works.
