### ISSUE TITLE
null values in Facebook Ads connector

### ISSUE THREAD

**Issue by evaldasjab** [mbilling/PBIConnectors#3]
Dear developers, i have an issue trying out your Facebook Ads data connector:
when i select my Ad account and select "Facebok All Ad Insights",i get empty rows instead of campaign data (screenshot in my [Dropbox](https://www.dropbox.com/s/t34t9a0bl0e249g/FacebookAds_DataCon_null.PNG)).
The number of empty rows does not match the number of campaigns in Facebook.

Any ideas, why it could be?
The campaigns are very old, made in 2014. Could that be the reason?..

**Comment by mbilling** [comment]
Could you test with the latest version if you still experience the described issue?

**Comment by evaldasjab** [comment]
Hi, "Facebook All Ad Insights" now imports all data, but also shows an error: 
"1 of the loaded queries contained errors. 222 rows loaded. 221 errors." (screenshot in my [Dropbox](https://www.dropbox.com/s/ww3ohih6qjsb5nx/FacebookAds_All.Ad.Insights_load.error.PNG?dl=0))

When i click on "View errors", it directs me to a blank Report page.

Issues with other options:
- "Active Ad Insights" shows only an empty column with the header "List", although i have one on-going campaign.
- "Ad Action Values" makes an empty table with columns "facebook_ad_key", "date",..., "Connector Has Error", "Connector Error Reason", "Connector Error Message".

**Comment by mbilling** [comment]
"Facebook All Ad Insights" works for me. Do you use your own API key? Sounds like a permission problem. These 221 rows could be one for each /insights call. One error per ad

"Active Ad Insights" Do you get any errors here?
"Ad Action Values" Can be empty when you don't have offsite_conversions from facebook pixel or uploaded offline_conversions. Does that makes sense?

**Comment by evaldasjab** [comment]
I use your connector and login with my Facebook account.
I have all permissions to access my ad manager.

No errors on "Active Ad Insights", just an empty column.
I think i don't use offsite_conversions, but in the previous connector version "Action Values" worked fine...
I'll check it with the older connector again.
