### ISSUE TITLE
Multiple Instagram Accounts

### ISSUE THREAD

**Issue by 0xMostafa** [mbilling/PBIConnectors#33]
First, Thank you for this project, really helped me a lot. Thank you.

I have multiple Instagram accounts, I connected to one and it worked perfectly.

Is there a way to connect multiple Instagram accounts with your connector?

**Comment by ruesaintdenis** [comment]
Hi @0xMostafa would you be available to help me set up my Instagram? I'm happy to pay for the help!

**Comment by 0xMostafa** [comment]
@ruesaintdenis sure, contact me [here](https://mailhide.io/e/rnaieZ1H)
