### ISSUE TITLE
error in Facebook Ads template

### ISSUE THREAD

**Issue by evaldasjab** [mbilling/PBIConnectors#4]
Dear developers, i have an issue trying out your Facebook Ads template:
when i open the Power BI file, i get an error "Expression.Error: The import Facebook Ads.Ads matches no exports. Did you miss a module reference?"
(screenshot in my [Dropbox](https://www.dropbox.com/s/9j57gwpe1ftap2g/FacebookAds_Template_error.PNG)).

Any ideas, why it could be?

**Comment by mbilling** [comment]
Hi, Thanks for your feedback!
I’ll look into this problem and do whatever needs to be done.
Michael

**Comment by mbilling** [comment]
You need to install the Facebook Ads connector before the template will work.
