### ISSUE TITLE
Can't sign in as different user in the Facebook Ads connector

### ISSUE THREAD

**Issue by evaldasjab** [mbilling/PBIConnectors#5]
Dear developers, i have another issue trying out your Facebook Ads data connector:
once i signed in with one Facebook account, i can't change it.

In the "Connect" window which writes"You are currently signed in", 
when i click the button "Sign in as different user", it writes "You are being signed in" for a moment 
and then "You are currently signed in" again.

In Data source settings -> Global permissions i deleted the "FacebookAds" permission.
Then the "Connect" window writes "You aren't signed in", 
but once i click on "Sign in", i'm immediately signed in to the same account again.

Please advice!

**Comment by mbilling** [comment]
You need to connect with the built-in Facebook connector to
sign-out/reconnect then you can choose another account. This workaround is
due to the PBI connector design
Cheers,
Michael


søn. 5. aug. 2018 kl. 19.23 skrev evaldasjab <notifications@github.com>:

**Comment by evaldasjab** [comment]
Thank you, that worked.
