### ISSUE TITLE
Another app for Facebook Ads connector

### ISSUE THREAD

**Issue by evaldasjab** [mbilling/PBIConnectors#6]
Dear Developers, i noticed that your Facebook Ads connector uses your app ID and app secret.
I would like to change it to my own app, just in case yours stops working.

I created an app on Facebook, added "Facebook Login" and "Marketing API" products there.
In the "Facebook Login" settings, i added [https://oauth.powerbi.com/views/oauthredirect.html](https://oauth.powerbi.com/views/oauthredirect.html) to "Valid OAuth Redirect URIs".

But when i try to sign in in Power BI using my modified connector (with updated client ID and client secret), Facebook shows an error:
"URL blocked: This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings. Make sure that the client and web OAuth logins are on and add all your app domains as valid OAuth redirect URIs."

Do you have an idea what could be wrong?..

**Comment by mbilling** [comment]
You need to add the URL to the "Valid OAuth Redirect URIs" in your Facebook App. 
You find it under "Facebook Login"/Settings

**Comment by evaldasjab** [comment]
I did it, but Facebook doesn't want to save changes - when i click "Save Changes", Valid OAuth Redirect URIs field becomes empty again...

**Comment by mbilling** [comment]
![image](https://user-images.githubusercontent.com/973790/44787066-5ee04400-ab96-11e8-8bb5-ebb57523de44.png)
My Facebook settings - to compare :)
