### ISSUE TITLE
Instagram connector is returning only zeros.

### ISSUE THREAD

**Issue by rudivs** [mbilling/PBIConnectors#8]
The Instagram connector returns no data for any of the columns (every row has a zero value for every column). In your [instructions](https://github.com/mbilling/PBIConnectors#the-instagram-connector) it seems that your data is also only zeros (although it could be that the demo account did not have any posts). 

The image below shows that the entire impressions column has only zero items. The same is true for every other column.

![image](https://user-images.githubusercontent.com/1894530/46351036-a4d96d80-c656-11e8-986f-6c234c2a9a3e.png)

**Comment by rudivs** [comment]
I tested in Graph API Explorer and it's showing zeros there too. If I look in the Instagram app itself it's showing N/A for all the insights fields, so it seems that the problem is with my account, not with the connector. Probably it only starts collecting data from when you set your account as a Business Account.

**Comment by mbilling** [comment]
hi @rudivs - you're probably right about that.
Let me know how it work out :)
